### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by liuyangjun-20** [AxlanderD/FaceRecognitionProject#1]
Mxnet 1.4.0-cu90
是不是mxnet-cu90 1.4.0（mxnet_cu90-1.4.0-py2.py3-none-win_amd64.whl (303.3 MB)）这个？

**Comment by liuyangjun-20** [comment]
model文件是不是需要自己创建，facenet和mtcnn的预训练模型需要哪个，facenet需要20170512-110547还是20180402-114759？

**Comment by liuyangjun-20** [comment]
您好，我根据我的cudn版本下载不下来mxnet，用pip下载whl文件也不行，会出现很多红色的报错，请问怎么办？？

**Comment by liuyangjun-20** [comment]
你好，我都配置完了，运行起来之后点击本地摄像头没反应

**Comment by liuyangjun-20** [comment]
您好，可以运行GraProject.py，但是没法用

**Comment by liuyangjun-20** [comment]
您好（hello）
mxnet.base.MXNetError: [13:53:23] c:\ci\libmxnet_1533398173145\work\3rdparty\dmlc-core\include\dmlc\./json.h:730: Check failed: ch == '{' (60 vs. {) Error at Line 6, around ^`!DOCTYPE html>`, Expect '{' but get '<'
请问这个问题怎么解决？（Could you tell me how to solve this problem
？）

**Comment by AxlanderD** [comment]
Sorry, 很抱歉现在才回复你。最后这个问题我没有遇到过。根据错误提示来看是因为配置文件中的语法错误
 `^!DOCTYPE html>, Expect '{' but get '<'`
